### ISSUE TITLE
Is there a translation into German? 

### ISSUE THREAD

**Issue by SDS1234** [Freenove/Freenove_Ultimate_Starter_Kit#3]
Good day,
I have a question regarding the tutorial or the instructions. Are they available in languages other than English? I needed a German translation. 

I would be very happy to receive an answer. 

With kind regards 
SDS

**Comment by DenzelChen** [comment]
Hi SDS,
Please contact us via support@freenove.com
We will send you a German version tutorial.
Sincerely,
Freenove

**Comment by SDS1234** [comment]
> Hi SDS,
> Please contact us via support@freenove.com
> We will send you a German version tutorial.
> Sincerely,
> Freenove

Hello,
I have done this, the support could not give me a German version either
